/* tslint:disable */
/* eslint-disable */
/**
 * Game^3 API
 * Game^3 API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Game
 */
export interface Game {
    /**
     * ゲームID
     * @type {string}
     * @memberof Game
     */
    id: string;
    /**
     * タームID
     * @type {string}
     * @memberof Game
     */
    termId: string;
    /**
     * DiscordのユーザーID
     * @type {string}
     * @memberof Game
     */
    discordUserId: string;
    /**
     * 公開されているかどうか
     * @type {boolean}
     * @memberof Game
     */
    isPublished: boolean;
    /**
     * 展示するゲームタイトル
     * @type {string}
     * @memberof Game
     */
    title: string;
    /**
     * ゲーム作成者
     * @type {string}
     * @memberof Game
     */
    creatorName: string;
    /**
     * 団体の代表者名
     * @type {string}
     * @memberof Game
     */
    representativeName: string;
    /**
     * 学生団体かどうか
     * @type {boolean}
     * @memberof Game
     */
    isStudentOrganization: boolean;
    /**
     * 当日のチーム人数
     * @type {number}
     * @memberof Game
     */
    teamSize: number;
    /**
     * ゲーム作成者のページのURL
     * @type {string}
     * @memberof Game
     */
    creatorPageUrl?: string;
    /**
     * ゲームページのURL
     * @type {string}
     * @memberof Game
     */
    gamePageUrl?: string;
    /**
     * ゲームの説明
     * @type {string}
     * @memberof Game
     */
    description: string;
    /**
     * ゲームビルドが提出されているかどうか
     * @type {boolean}
     * @memberof Game
     */
    hasBuild: boolean;
    /**
     * 展示場所
     * @type {string}
     * @memberof Game
     */
    place?: string;
}

/**
 * Check if a given object implements the Game interface.
 */
export function instanceOfGame(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "termId" in value;
    isInstance = isInstance && "discordUserId" in value;
    isInstance = isInstance && "isPublished" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "creatorName" in value;
    isInstance = isInstance && "representativeName" in value;
    isInstance = isInstance && "isStudentOrganization" in value;
    isInstance = isInstance && "teamSize" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "hasBuild" in value;

    return isInstance;
}

export function GameFromJSON(json: any): Game {
    return GameFromJSONTyped(json, false);
}

export function GameFromJSONTyped(json: any, ignoreDiscriminator: boolean): Game {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'termId': json['termId'],
        'discordUserId': json['discordUserId'],
        'isPublished': json['isPublished'],
        'title': json['title'],
        'creatorName': json['creatorName'],
        'representativeName': json['representativeName'],
        'isStudentOrganization': json['isStudentOrganization'],
        'teamSize': json['teamSize'],
        'creatorPageUrl': !exists(json, 'creatorPageUrl') ? undefined : json['creatorPageUrl'],
        'gamePageUrl': !exists(json, 'gamePageUrl') ? undefined : json['gamePageUrl'],
        'description': json['description'],
        'hasBuild': json['hasBuild'],
        'place': !exists(json, 'place') ? undefined : json['place'],
    };
}

export function GameToJSON(value?: Game | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'termId': value.termId,
        'discordUserId': value.discordUserId,
        'isPublished': value.isPublished,
        'title': value.title,
        'creatorName': value.creatorName,
        'representativeName': value.representativeName,
        'isStudentOrganization': value.isStudentOrganization,
        'teamSize': value.teamSize,
        'creatorPageUrl': value.creatorPageUrl,
        'gamePageUrl': value.gamePageUrl,
        'description': value.description,
        'hasBuild': value.hasBuild,
        'place': value.place,
    };
}

