/* tslint:disable */
/* eslint-disable */
/**
 * Game^3 API
 * Game^3 API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Game
 */
export interface Game {
    /**
     * ゲームID
     * @type {string}
     * @memberof Game
     */
    id: string;
    /**
     * ブース展示者名
     * @type {string}
     * @memberof Game
     */
    creatorName: string;
    /**
     * 所属団体
     * @type {string}
     * @memberof Game
     */
    organization?: string;
    /**
     * Twitter ID
     * @type {string}
     * @memberof Game
     */
    twitterId?: string;
    /**
     * Webサイト等のURL
     * @type {string}
     * @memberof Game
     */
    websiteUrl?: string;
    /**
     * 展示するゲームタイトル
     * @type {string}
     * @memberof Game
     */
    title: string;
    /**
     * 展示するゲームのジャンル
     * @type {string}
     * @memberof Game
     */
    genre?: string;
    /**
     * ゲームの開発環境
     * @type {string}
     * @memberof Game
     */
    developmentEnvironment?: string;
    /**
     * ゲームの説明
     * @type {string}
     * @memberof Game
     */
    description?: string;
    /**
     * 用語
     * @type {string}
     * @memberof Game
     */
    term?: string;
    /**
     * イベントID
     * @type {string}
     * @memberof Game
     */
    eventId?: string;
    /**
     * DiscordのユーザーID
     * @type {string}
     * @memberof Game
     */
    discordUserId?: string;
}

/**
 * Check if a given object implements the Game interface.
 */
export function instanceOfGame(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "creatorName" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function GameFromJSON(json: any): Game {
    return GameFromJSONTyped(json, false);
}

export function GameFromJSONTyped(json: any, ignoreDiscriminator: boolean): Game {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'creatorName': json['creatorName'],
        'organization': !exists(json, 'organization') ? undefined : json['organization'],
        'twitterId': !exists(json, 'twitterId') ? undefined : json['twitterId'],
        'websiteUrl': !exists(json, 'websiteUrl') ? undefined : json['websiteUrl'],
        'title': json['title'],
        'genre': !exists(json, 'genre') ? undefined : json['genre'],
        'developmentEnvironment': !exists(json, 'developmentEnvironment') ? undefined : json['developmentEnvironment'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'term': !exists(json, 'term') ? undefined : json['term'],
        'eventId': !exists(json, 'eventId') ? undefined : json['eventId'],
        'discordUserId': !exists(json, 'discordUserId') ? undefined : json['discordUserId'],
    };
}

export function GameToJSON(value?: Game | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'creatorName': value.creatorName,
        'organization': value.organization,
        'twitterId': value.twitterId,
        'websiteUrl': value.websiteUrl,
        'title': value.title,
        'genre': value.genre,
        'developmentEnvironment': value.developmentEnvironment,
        'description': value.description,
        'term': value.term,
        'eventId': value.eventId,
        'discordUserId': value.discordUserId,
    };
}

