/* tslint:disable */
/* eslint-disable */
/**
 * Game^3 API
 * Game^3 API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchEventRequest
 */
export interface PatchEventRequest {
    /**
     * slug (URL内で使用, unique) 18th等
     * @type {string}
     * @memberof PatchEventRequest
     */
    slug?: string;
    /**
     * 第18回
     * @type {string}
     * @memberof PatchEventRequest
     */
    title?: string;
    /**
     * ゲーム展示の募集期間
     * @type {Date}
     * @memberof PatchEventRequest
     */
    gameSubmissionPeriodStart?: Date;
    /**
     * ゲーム展示の募集期間
     * @type {Date}
     * @memberof PatchEventRequest
     */
    gameSubmissionPeriodEnd?: Date;
    /**
     * パンフレット用画像
     * @type {Blob}
     * @memberof PatchEventRequest
     */
    image?: Blob;
}

/**
 * Check if a given object implements the PatchEventRequest interface.
 */
export function instanceOfPatchEventRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchEventRequestFromJSON(json: any): PatchEventRequest {
    return PatchEventRequestFromJSONTyped(json, false);
}

export function PatchEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchEventRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'gameSubmissionPeriodStart': !exists(json, 'gameSubmissionPeriodStart') ? undefined : (new Date(json['gameSubmissionPeriodStart'])),
        'gameSubmissionPeriodEnd': !exists(json, 'gameSubmissionPeriodEnd') ? undefined : (new Date(json['gameSubmissionPeriodEnd'])),
        'image': !exists(json, 'image') ? undefined : json['image'],
    };
}

export function PatchEventRequestToJSON(value?: PatchEventRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'title': value.title,
        'gameSubmissionPeriodStart': value.gameSubmissionPeriodStart === undefined ? undefined : (value.gameSubmissionPeriodStart.toISOString()),
        'gameSubmissionPeriodEnd': value.gameSubmissionPeriodEnd === undefined ? undefined : (value.gameSubmissionPeriodEnd.toISOString()),
        'image': value.image,
    };
}

