/* tslint:disable */
/* eslint-disable */
/**
 * Game^3 API
 * Game^3 API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostEventRequest
 */
export interface PostEventRequest {
    /**
     * URL
     * @type {string}
     * @memberof PostEventRequest
     */
    slug: string;
    /**
     * 第18回
     * @type {string}
     * @memberof PostEventRequest
     */
    title: string;
    /**
     * ゲーム展示の募集期間
     * @type {Date}
     * @memberof PostEventRequest
     */
    gameSubmissionPeriodStart?: Date;
    /**
     * ゲーム展示の募集期間
     * @type {Date}
     * @memberof PostEventRequest
     */
    gameSubmissionPeriodEnd?: Date;
}

/**
 * Check if a given object implements the PostEventRequest interface.
 */
export function instanceOfPostEventRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "slug" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function PostEventRequestFromJSON(json: any): PostEventRequest {
    return PostEventRequestFromJSONTyped(json, false);
}

export function PostEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostEventRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'title': json['title'],
        'gameSubmissionPeriodStart': !exists(json, 'gameSubmissionPeriodStart') ? undefined : (new Date(json['gameSubmissionPeriodStart'])),
        'gameSubmissionPeriodEnd': !exists(json, 'gameSubmissionPeriodEnd') ? undefined : (new Date(json['gameSubmissionPeriodEnd'])),
    };
}

export function PostEventRequestToJSON(value?: PostEventRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'title': value.title,
        'gameSubmissionPeriodStart': value.gameSubmissionPeriodStart === undefined ? undefined : (value.gameSubmissionPeriodStart.toISOString()),
        'gameSubmissionPeriodEnd': value.gameSubmissionPeriodEnd === undefined ? undefined : (value.gameSubmissionPeriodEnd.toISOString()),
    };
}

