/* tslint:disable */
/* eslint-disable */
/**
 * Game^3 API
 * Game^3 API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostTermRequest
 */
export interface PostTermRequest {
    /**
     * イベントのslug
     * @type {string}
     * @memberof PostTermRequest
     */
    eventSlug: string;
    /**
     * タームが始まる時間
     * @type {Date}
     * @memberof PostTermRequest
     */
    startAt: Date;
    /**
     * タームが終わる時間
     * @type {Date}
     * @memberof PostTermRequest
     */
    endAt: Date;
}

/**
 * Check if a given object implements the PostTermRequest interface.
 */
export function instanceOfPostTermRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "eventSlug" in value;
    isInstance = isInstance && "startAt" in value;
    isInstance = isInstance && "endAt" in value;

    return isInstance;
}

export function PostTermRequestFromJSON(json: any): PostTermRequest {
    return PostTermRequestFromJSONTyped(json, false);
}

export function PostTermRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTermRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eventSlug': json['eventSlug'],
        'startAt': (new Date(json['startAt'])),
        'endAt': (new Date(json['endAt'])),
    };
}

export function PostTermRequestToJSON(value?: PostTermRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eventSlug': value.eventSlug,
        'startAt': (value.startAt.toISOString()),
        'endAt': (value.endAt.toISOString()),
    };
}

