/* tslint:disable */
/* eslint-disable */
/**
 * Game^3 API
 * Game^3 API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUser
 */
export interface UserUser {
    /**
     * 
     * @type {string}
     * @memberof UserUser
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUser
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUser
     */
    profileImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUser
     */
    role?: string;
}

/**
 * Check if a given object implements the UserUser interface.
 */
export function instanceOfUserUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserUserFromJSON(json: any): UserUser {
    return UserUserFromJSONTyped(json, false);
}

export function UserUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'profileImageUrl': !exists(json, 'profileImageUrl') ? undefined : json['profileImageUrl'],
        'role': !exists(json, 'role') ? undefined : json['role'],
    };
}

export function UserUserToJSON(value?: UserUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'username': value.username,
        'profileImageUrl': value.profileImageUrl,
        'role': value.role,
    };
}

