/* tslint:disable */
/* eslint-disable */
/**
 * Game^3 API
 * Game^3 API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PostContactsRequest,
} from '../models/index';
import {
    PostContactsRequestFromJSON,
    PostContactsRequestToJSON,
} from '../models/index';

export interface PostContactsOperationRequest {
    postContactsRequest: PostContactsRequest;
}

/**
 * 
 */
export class ContactsApi extends runtime.BaseAPI {

    /**
     * コンタクト用メールを送信
     */
    async postContactsRaw(requestParameters: PostContactsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.postContactsRequest === null || requestParameters.postContactsRequest === undefined) {
            throw new runtime.RequiredError('postContactsRequest','Required parameter requestParameters.postContactsRequest was null or undefined when calling postContacts.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/contacts`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostContactsRequestToJSON(requestParameters.postContactsRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * コンタクト用メールを送信
     */
    async postContacts(requestParameters: PostContactsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postContactsRaw(requestParameters, initOverrides);
    }

}
